#!/usr/bin/env python3
"""Export a conservative LilyPond source for simple MusicXML scores."""

from __future__ import annotations

import argparse
from pathlib import Path

try:
    from .common import open_musicxml, safe_int
except ImportError:
    from common import open_musicxml, safe_int


STEP_NAMES = {"C": "c", "D": "d", "E": "e", "F": "f", "G": "g", "A": "a", "B": "b"}


def lily_pitch(pitch) -> str:
    name = STEP_NAMES[pitch.findtext("step")]
    alter = safe_int(pitch.findtext("alter"), 0)
    name += "is" * max(alter, 0) + "es" * max(-alter, 0)
    octave = int(pitch.findtext("octave"))
    return name + ("'" * max(0, octave - 3)) + ("," * max(0, 3 - octave))


def lily_duration(note, divisions: int) -> str:
    value = float(note.findtext("duration", "0")) / max(divisions, 1)
    common = {4: "1", 2: "2", 1: "4", 0.5: "8", 0.25: "16", 1.5: "4.", 3: "2.", 6: "1."}
    return common.get(value, "4")


def export(source: str, target: str) -> dict:
    tree, _ = open_musicxml(source)
    root = tree.getroot()
    parts = []
    for part in root.findall("part"):
        items = []
        divisions = 1
        for measure in part.findall("measure"):
            div = measure.find("./attributes/divisions")
            if div is not None:
                divisions = safe_int(div.text, divisions)
            for note in measure.findall("note"):
                if note.find("chord") is not None:
                    continue
                duration = lily_duration(note, divisions)
                if note.find("rest") is not None:
                    items.append(f"r{duration}")
                elif note.find("pitch") is not None:
                    items.append(f"{lily_pitch(note.find('pitch'))}{duration}")
        parts.append(" ".join(items))
    warnings = []
    if len(parts) != 1:
        warnings.append("basic exporter emits one independent staff per part; complex voice alignment requires manual review")
    if root.findall(".//note[chord]") or root.findall(".//backup") or root.findall(".//forward"):
        warnings.append("chords or polyphonic timing were simplified; inspect the .ly source")
    content = "\\version \"2.24.0\"\n% Generated by score-transposer; verify notation before engraving.\n\\score {\n"
    if len(parts) == 1:
        content += f"  {{ {parts[0]} }}\n"
    else:
        content += "  <<\n" + "\n".join(f"    \\new Staff {{ {part} }}" for part in parts) + "\n  >>\n"
    content += "}\n"
    Path(target).write_text(content, encoding="utf-8")
    return {"source": source, "target": target, "parts": len(parts), "warnings": warnings, "passed": True}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", required=True)
    parser.add_argument("--target", required=True)
    args = parser.parse_args()
    result = export(args.source, args.target)
    print(result)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
